export const UPDATE_QUANTITY='UPDATE_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ACTIVATE_DISCOUNT = 'ACTIVATE_DISCOUNT'
export const DEACTIVATE_DISCOUNT = 'DEACTIVATE_DISCOUNT'